apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backend.serviceAccountName }}
  namespace: {{ .Values.backend.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.backend.irsaRoleArn }}
