apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.frontend.serviceAccountName }}
  namespace: {{ .Values.frontend.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.frontend.irsaRoleArn }}
